proper echo to stderr

diff --git a/bin/pf-move-sshban-to-black b/bin/pf-move-sshban-to-black
--- a/bin/pf-move-sshban-to-black
+++ b/bin/pf-move-sshban-to-black
@@ -32,7 +32,7 @@
 SCRIPTVERSION=150101-082359
 
 if ! which pf-table >/dev/null 2>&1; then
-  echo "pf-table not found" >2
+  echo "ERROR: Missing $i." >&2
   exit 1  
 fi
 
